version: "3.8"
services:

  backend:
    build:
      context: ./IM-BACKEND
      dockerfile: Dockerfile
      cache_from:
        - node:20-alpine
    container_name: IM-BACKEND
    ports:
      - "6600:6600"
      - "10000-10100:10000-10100/udp"
      - "10000-10100:10000-10100/tcp"
    environment:
      - NODE_ENV=production
    env_file:
      - ./IM-BACKEND/.env.production
    volumes:
      - ./IM-BACKEND/logs:/usr/src/app/logs

networks:
  app-network:
    driver: bridge